name: 'Tests: node.js >= 20'

on: [pull_request, push]

permissions:
  contents: read

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '>= 20'
      type: minors
      command: npm run tests-only
